line-length = 40

lint.select = [
    # if adding a rule here that affects a sizeable portion of a codebase - consider adding it to ruff.precommit.toml first.
    "ANN001",
    "C4",
    "COM818",
    "E711",
    "E712",
    "E713",
    "E714",
    "E721",
    "E722",
    "E731",
    "E902",
    "F401",
    "F402",
    "F403",
    "F404",
    "F405",
    "F811",
    "F821",
    "F822",
    "F823",
    "F841",
    "F901",
    "G010",
    "I",
    "N",
    "PGH003",
    "PLC3002",
    "PLE0101",
    "PLE0116",
    "PLE0117",
    "PLE0241",
    "PLE0302",
    "PLE0604",
    "PLE0605",
    "PLE1142",
    "PLE1205",
    "PLE1206",
    "PLE1307",
    "PLE1310",
    "PLE1507",
    "PLE2502",
    "PLE2510",
    "PLE2512",
    "PLE2513",
    "PLE2514",
    "PLE2515",
    "PLR0124",
    "PLR0133",
    "PLR0206",
    "PLR1711",
    "PLW0120",
    "PLW0127",
    "PLW0129",
    "PLW0131",
    "PLW0406",
    "PLW0603",
    "PLW0711",
    "PLW1508",
    "PLW1509",
    "PLW2901",
    "PLW3301",
    "S",
    "T100",
    "TD",
    "TID251",
    "UP004",
    "UP006",
    "UP009",
    "UP025",
    "UP026",
    "W191",
    "W291",
    "W292",
    "W293",
    "W605",
]

lint.ignore = [
    "C413",
    "E266",
    "E741",
    "N811",
    "N813",
    "N818",
    "S101",
    "S104",
    "S110",
    "S113",
    "S311",
    "TD002",
    "TD004"
]
